# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

version: 2.1
jobs:
  build:
    docker:
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/clojure:lein-2.9.1


    working_directory: ~/crux

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: lein sub install
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run: lein do version, check

      # one for when we can get CircleCI Clojars deploys working again
      # - run: ./.circleci/bin/deploy_clojars.sh

  deploy:
    docker:
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/clojure:lein-2.9.1

    working_directory: ~/crux
    steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "project.clj" }}
              - v1-dependencies-
        - run: lein sub install
        - run: lein deps

        - save_cache:
            paths:
              - ~/.m2
            key: v1-dependencies-{{ checksum "project.clj" }}

        - run: sh ./crux-bench/bin/download_dataset.sh
        - run: lein sub -s crux-bench uberjar
        - run:
            command: |
              echo 'export BUILD_ARG="--build-arg crux_commit=$CIRCLE_SHA1"' >> $BASH_ENV
              echo 'export BUILD_TAGS="master,commit-$CIRCLE_SHA1"' >> $BASH_ENV

        - setup_remote_docker
        - aws-ecr/build-and-push-image:
              dockerfile: 'Dockerfile'
              extra-build-args: '${BUILD_ARG}'
              path: "crux-bench/"
              repo: 'crux-bench'
              tag: '${BUILD_TAGS}'

  create-uberjars:
    docker:
      - image: circleci/clojure:lein-2.9.1
    working_directory: ~/crux
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein sub -s crux-cli uberjar
      - run: mkdir crux-cli/jars/
      - run: cp crux-cli/target/*-standalone.jar crux-cli/jars/
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  deploy-uberjars:
    docker:
      - image: cibuilds/github:0.10
    working_directory: ~/crux
    steps:
      - attach_workspace:
          at: ./
      - run:
          command: |
            ghr -t "${GITHUB_TOKEN}" -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}" -c "${CIRCLE_SHA1}" -delete "${CIRCLE_TAG}" "./crux-cli/jars/"

  deploy-docker:
    docker:
      - image: docker:19.03.5
    working_directory: ~/crux
    steps:
      - attach_workspace:
          at: ./
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            cd crux-cli/
            docker build -t "danmason/crux-standalone:latest" .
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker push "danmason/crux-standalone:latest"


workflows:
  version: 2.1
  commit:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - create-uberjars:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy-uberjars:
          requires:
            - create-uberjars
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy-docker:
          requires:
            - create-uberjars
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
